services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    container_name: app-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app-backend
    ports:
      - '3120:3120'
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7-alpine
    container_name: app-redis
    ports:
      - '6379:6379'
